version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: commercial-banks
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: commercial-banks

	commercial-banks:
		build: .
		image: chamaconekt/commercial-banks
		links:
		- postgres
		container_name: commercial-banks
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- commercial-banks
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/commercial-banks-nginx/nginx.conf
		depends_on:
			- commercial-banks
		ports:
			- 80:80
		volumes_from:
			- commercial-banks

volumes:
	commercial-banks-static-files:
		driver:local